from river import stream
from river.datasets import base


class ReutersK500(base.RemoteDataset):
    """
    This dataset is a well-known benchmark for text classification methods. It has 5 subsets, each one with 6000 articles assigned into one or more of 101 topics.

    David D. Lewis, Yiming Yang, Tony G. Rose, and Fan Li. RCV1: A new benchmark collection for text categorization research. Journal of Machine Learning Research, 5:361-397, 2004.
    """

    def __init__(self):
        super().__init__(
            task=base.MO_BINARY_CLF,
            n_samples=6000,
            n_features=500,
            n_outputs=103,
            url="http://www.uco.es/grupos/kdis/MLLResources/ucobigfiles/Datasets/Full/Reuters-K500_Meka.zip",
            unpack=True,
            filename="Reuters-K500.arff",
            size=690_992,
        )

    def _iter(self):
        return stream.iter_arff(
            self.path,
            sparse=True,
            target=[
                "CCAT.CCAT",
                "CCAT.C11",
                "CCAT.C12",
                "CCAT.C13",
                "CCAT.C14",
                "CCAT.C15.C15",
                "CCAT.C15.C151.C151",
                "CCAT.C15.C151.C1511",
                "CCAT.C15.C152",
                "CCAT.C16",
                "CCAT.C17.C17",
                "CCAT.C17.C171",
                "CCAT.C17.C172",
                "CCAT.C17.C173",
                "CCAT.C17.C174",
                "CCAT.C18.C18",
                "CCAT.C18.C181",
                "CCAT.C18.C182",
                "CCAT.C18.C183",
                "CCAT.C21",
                "CCAT.C22",
                "CCAT.C23",
                "CCAT.C24",
                "CCAT.C31.C31",
                "CCAT.C31.C311",
                "CCAT.C31.C312",
                "CCAT.C31.C313",
                "CCAT.C32",
                "CCAT.C33.C33",
                "CCAT.C33.C331",
                "CCAT.C34",
                "CCAT.C41.C41",
                "CCAT.C41.C411",
                "CCAT.C42",
                "ECAT.ECAT",
                "ECAT.E11",
                "ECAT.E12.E12",
                "ECAT.E12.E121",
                "ECAT.E13.E13",
                "ECAT.E13.E131",
                "ECAT.E13.E132",
                "ECAT.E14.E14",
                "ECAT.E14.E141",
                "ECAT.E14.E142",
                "ECAT.E14.E143",
                "ECAT.E21.E21",
                "ECAT.E21.E211",
                "ECAT.E21.E212",
                "ECAT.E31.E31",
                "ECAT.E31.E311",
                "ECAT.E31.E312",
                "ECAT.E31.E313",
                "ECAT.E41.E41",
                "ECAT.E41.E411",
                "ECAT.E51.E51",
                "ECAT.E51.E511",
                "ECAT.E51.E512",
                "ECAT.E51.E513",
                "ECAT.E61",
                "ECAT.E71",
                "GCAT.G15.G15",
                "GCAT.G15.G151",
                "GCAT.G15.G152",
                "GCAT.G15.G153",
                "GCAT.G15.G154",
                "GCAT.G15.G155",
                "GCAT.G15.G156",
                "GCAT.G15.G157",
                "GCAT.G15.G158",
                "GCAT.G15.G159",
                "GCAT.GCAT",
                "GCAT.GCRIM",
                "GCAT.GDEF",
                "GCAT.GDIP",
                "GCAT.GDIS",
                "GCAT.GENT",
                "GCAT.GENV",
                "GCAT.GFAS",
                "GCAT.GHEA",
                "GCAT.GJOB",
                "GCAT.GMIL",
                "GCAT.GOBIT",
                "GCAT.GODD",
                "GCAT.GPOL",
                "GCAT.GPRO",
                "GCAT.GREL",
                "GCAT.GSCI",
                "GCAT.GSPO",
                "GCAT.GTOUR",
                "GCAT.GVIO",
                "GCAT.GVOTE",
                "GCAT.GWEA",
                "GCAT.GWELF",
                "MCAT.MCAT",
                "MCAT.M11",
                "MCAT.M12",
                "MCAT.M13.M13",
                "MCAT.M13.M131",
                "MCAT.M13.M132",
                "MCAT.M14.M14",
                "MCAT.M14.M141",
                "MCAT.M14.M142",
                "MCAT.M14.M143",
            ],
        )
